# SPDX-License-Identifier: CC0-1.0
 - id: meson test
   name: meson test
   description: Run all meson tests
   entry: meson test -C build/
   language: system
   always_run: true
   pass_filenames: false
